version: 0.2

env:
  variables:
    AWS_ACCOUNT_ID: 372241483606
    AWS_REGION: us-east-1
    REPOSITORY_NAME: mycicdprojectrepository

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo Installing Maven...
      - yum install -y maven
      - echo Installing Docker client...
      - yum install -y docker
      - echo Starting Docker service...
      - service docker start

  pre_build:
    commands:
      - echo Logging into Amazon ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com

  build:
    commands:
      - echo Building Spring Boot application...
      - mvn clean package
      - echo Building Docker image...
      - docker build -t $REPOSITORY_NAME -f Dockerfile .
      - docker tag $REPOSITORY_NAME:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$REPOSITORY_NAME:latest
      - echo Showing Docker images list...
      - docker images

  post_build:
    commands:
      - echo Re-Logging into Amazon ECR before push...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
      - echo Pushing Docker image to ECR...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$REPOSITORY_NAME:latest
      - echo Creating imagedefinitions.json for ECS deployment...
      - printf '[{"name":"springboot-container","imageUri":"%s"}]' "$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$REPOSITORY_NAME:latest" > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json
